In [12]:
#Question 1 - Solution 1
def isPalindrome1 (word):
    word = word.lower()
    reverseWord = word[::-1]
    if (word == reverseWord):
        return True
    return False

print( isPalindrome1("Rotator") )
print( isPalindrome1("Ey Edip Adanada pide ye") )

#Question 1 - Solution 2
def reverse(word):
    result=""
    for x in range(len(word)):
        result += word[len(word)-1 - x]
    return result

print( reverse("Sabancı Üniversity") )

def isPalindrome1 (word):
    word = word.lower()
    reverseWord = reverse(word)
    if (word == reverseWord):
        return True
    return False

print( isPalindrome1("Rotator") )
print( isPalindrome1("Ey Edip Adanada pide ye") )

True
True
ytisrevinÜ ıcnabaS
True
True


In [17]:
#Question 2 - Solution 1
def lastLetterToUppercase(text):
    words = text.split(" ")
    result=""
    for word in words:
        result += word[:-1] + word[-1].upper()+ " "
    return result.strip()

print( lastLetterToUppercase("evvel zaman içinde kalbur saman içinde" ) )

evveL zamaN içindE kalbuR samaN içindE


In [16]:
a = "Ahmet"
a[:-1] + a[-1].upper()

'AhmeT'

In [26]:
#Question 3 - Solution 1
def isPalindrome1 (word):
    word = word.lower()
    reverseWord = word[::-1]
    if (word == reverseWord):
        return True
    return False

def findLongestPalindrome(text):
    words  = text.split(" ")
    longest = ""
    for word in words:
        word = word.strip()
        isPalin = isPalindrome1(word)
        if (isPalin):
            if(len(longest)<=len(word)):
                longest = word
    return longest

print  ( findLongestPalindrome("Otoyolda   Rotator iki adet radar var ama arabada küllük yok radar rototor küllük"))    

rototor


In [40]:
#Question 4 - Solution 1

def printInfo1(products,prices,counts):
    for i in range(len(products)):
        print("We have "+ str( counts[i] ) +" "+products[i]+"s, each one is "+str(prices[i])
              +" TL and the total price is "+str ( counts[i]*prices[i] ) +" TL")
        
products = ["Computer","Table","Chair"] 
prices = [3000, 250, 80]
counts = [3, 2, 8]
print("-------------------------------Solution 1-----------------------------------")
printInfo1(products,prices,counts)

#Question 4 - Solution 1
def getInfo(products,prices,counts):
    result =""
    for i in range(len(products)):
        result += "We have "+ str( counts[i] ) +" "+products[i]+"s, each one is "+str(prices[i])+" TL and the total price is "+str ( counts[i]*prices[i] ) +" TL\n"
    return result
print("-------------------------------Solution 2-----------------------------------")
sonuc = getInfo(products,prices,counts)
print (sonuc)

-------------------------------Solution 1-----------------------------------
We have 3 Computers, each one is 3000 TL and the total price is 9000 TL
We have 2 Tables, each one is 250 TL and the total price is 500 TL
We have 8 Chairs, each one is 80 TL and the total price is 640 TL
-------------------------------Solution 2-----------------------------------
We have 3 Computers, each one is 3000 TL and the total price is 9000 TL
We have 2 Tables, each one is 250 TL and the total price is 500 TL
We have 8 Chairs, each one is 80 TL and the total price is 640 TL



In [65]:
#Question 5 - Solution 1
def sameLetterCheck1 (word1, word2):
    if (sorted(word1) == sorted(word2)):
        return True
    else:
        return False
    
print (  sameLetterCheck("meta", "tema") ) 
print (  sameLetterCheck("ekrem", "kerem") )
print (  sameLetterCheck("silah", "ihlas") )
print (  sameLetterCheck("maamut", "mammut") )


#Question 5 - Solution 2
def sameLetterCheck2 (word1, word2):
    if (len(word1) != len(word2)):
        return False
    harfler1 = list(word1)
    harfler2 = list(word2)
    for harf1 in harfler1:
        if harf1 in harfler2:
            harfler2.remove(harf1)
        print("Silinen : ",harf1, " -- kalan ",harfler2)
    if(len(harfler2)==0):
        return True
    else:
        return False
        
print (  sameLetterCheck2("maamut", "mammut") )        

True
True
True
False
Silinen :  m  -- kalan  ['a', 'm', 'u', 't']
Silinen :  a  -- kalan  ['m', 'u', 't']
Silinen :  m  -- kalan  ['u', 't']
Silinen :  u  -- kalan  ['t']
Silinen :  t  -- kalan  []
True


In [67]:
def sameLetterCheck(word1,word2):
    wordSet1 = set(word1)
    wordSet2 = set(word2)
    if (wordSet1 == wordSet2):
        for char in wordSet1:
            if(word1.count(char) != word2.count(char)):
                return False
            return True
        else:
            return False
sameLetterCheck("maamut", "mammut")

False

In [70]:
#Numpy Type Conversion
a = ["3.4","5.5","8.8"]
npA= np.array(a)
print(npA)
npA = npA.astype("float")
print(npA)

['3.4' '5.5' '8.8']
[3.4 5.5 8.8]


In [73]:
import numpy as np
x = np.arange(0,9).reshape(3,3)
print(x)
print ( x[:,2].astype("str") )

[[0 1 2]
 [3 4 5]
 [6 7 8]]
['2' '5' '8']
