In [5]:
import numpy as np

sayilar = [1,2,3,4,5]
n = []
for sayi in sayilar:
    n.append(sayi*sayi)
print(n)


[1, 4, 9, 16, 25]


In [6]:
npSayilar = np.array(sayilar)
n2 = npSayilar * 2
print(n2)

[ 2  4  6  8 10]


In [7]:
nKare = npSayilar * npSayilar
print(nKare)

[ 1  4  9 16 25]


In [11]:
dizi = np.arange(0,100)
matris = dizi.reshape(10,10)
print(matris)

[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]
 [50 51 52 53 54 55 56 57 58 59]
 [60 61 62 63 64 65 66 67 68 69]
 [70 71 72 73 74 75 76 77 78 79]
 [80 81 82 83 84 85 86 87 88 89]
 [90 91 92 93 94 95 96 97 98 99]]


In [13]:
print( matris[5,4:8] )

array([54, 55, 56, 57])

In [15]:
print ( matris[0,:] )

[0 1 2 3 4 5 6 7 8 9]


In [16]:
mat = np.arange(1,10)
mat = mat.reshape(3,3)
print(mat)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [17]:
identityM = np.eye(3,3)
print(identityM)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [20]:
sonuc = np.matmul(mat,identityM)
print(sonuc)

[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]


In [31]:
mat*identityM  #Elemen-wise multiplication

array([[1., 0., 0.],
       [0., 5., 0.],
       [0., 0., 9.]])

In [32]:
#Fancy indexing

a = np.arange(100,150)
print(a)



[100 101 102 103 104 105 106 107 108 109 110 111 112 113 114 115 116 117
 118 119 120 121 122 123 124 125 126 127 128 129 130 131 132 133 134 135
 136 137 138 139 140 141 142 143 144 145 146 147 148 149]


In [33]:
print(a[10])

110

In [35]:
print(a[[9,4,13]] )

[109 104 113]


In [36]:
b = [23, 33, 12, 43, 56, 32, 45, 67, 78, 90, 35]

bNP = np.array(b)



array([43, 56, 45, 67, 78, 90])

In [42]:
c = np.array([5,8,2])
print( c[[True,False,False]] )#Fancy Index

[5]


In [41]:
print ( bNP>88 )

[False False False False False False False False False  True False]


In [43]:
print( bNP[bNP>35])

[43 56 45 67 78 90]


In [47]:
np1 = np.arange(100,200)
np2 = np1.reshape(10,10)
print(np2)
print("Sadece 2. (index) kolon ",np2[:,2])

[[100 101 102 103 104 105 106 107 108 109]
 [110 111 112 113 114 115 116 117 118 119]
 [120 121 122 123 124 125 126 127 128 129]
 [130 131 132 133 134 135 136 137 138 139]
 [140 141 142 143 144 145 146 147 148 149]
 [150 151 152 153 154 155 156 157 158 159]
 [160 161 162 163 164 165 166 167 168 169]
 [170 171 172 173 174 175 176 177 178 179]
 [180 181 182 183 184 185 186 187 188 189]
 [190 191 192 193 194 195 196 197 198 199]]
Sadece 2. (index) kolon  [102 112 122 132 142 152 162 172 182 192]


In [49]:
print( np2[0:7:2,1:6:2] )

[[101 103 105]
 [121 123 125]
 [141 143 145]
 [161 163 165]]


In [81]:
ulkeSicaklik = np.loadtxt("fahrenheit.txt",delimiter=":",dtype="str")
#print(ulkeSicaklik)
yeni = np.array( ulkeSicaklik[:,1],dtype="int")
print(yeni)

[ 70  88  10 120 111 123   0  99  45  66  87  65  78  34  23]


In [64]:
koordinatlar = np.loadtxt("points.txt",delimiter=",")
print(koordinatlar)

[[ 5.  5.]
 [15. 17.]
 [15. 16.]
 [ 5.  6.]
 [ 6.  6.]
 [16. 16.]
 [ 7.  7.]
 [ 7.  6.]
 [17. 17.]
 [ 6.  7.]
 [ 7.  8.]
 [18. 18.]
 [ 8.  6.]
 [15. 18.]
 [ 5.  8.]
 [17. 16.]
 [ 8.  8.]
 [16. 17.]
 [17. 18.]
 [18. 16.]]


In [70]:
excel = np.loadtxt("deneme.csv",delimiter=";")
print(excel)

[[  123.    33.]
 [   44.   321.]
 [  343. 23323.]
 [  444.  4343.]
 [ 3223.   323.]]
